  server:
    port: 8080
    session-timeout: 30




  spring:
   # DATASOURCE
    datasource:
      driverClass: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/zhaopin?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 694310908

    thymeleaf:
      prefix: classpath:/template/
      suffix: .html

      mode: LEGACYHTML5
      encoding: UTF-8
      cache: false
      content-type: text/html
#
#  endpoints:
#      cors:
#          allowed-origins: *
#          allowed-methods: GET,POST
